/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MainApp {
    }
}
declare global {
    interface HTMLMainAppElement extends Components.MainApp, HTMLStencilElement {
    }
    var HTMLMainAppElement: {
        prototype: HTMLMainAppElement;
        new (): HTMLMainAppElement;
    };
    interface HTMLElementTagNameMap {
        "main-app": HTMLMainAppElement;
    }
}
declare namespace LocalJSX {
    interface MainApp {
    }
    interface IntrinsicElements {
        "main-app": MainApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "main-app": LocalJSX.MainApp & JSXBase.HTMLAttributes<HTMLMainAppElement>;
        }
    }
}
